### PR TITLE
Added mirror nethserver.interlin.nl/nethserver

### PR DESCRIPTION
**Pull request by robbosch**
See https://community.nethserver.org/t/how-to-create-your-own-nethserver-mirror/344/77?u=davidep

### CODE REVIEW

**Comment by robbosch** [comment]
The mirror is located in Germany (.de)

**Comment by DavidePrincipi** [comment]
Thank you @robbosch ! I added the mirror to the monitored pool: http://mirror-status.nethserver.org/

Let's check its state for a while before pushing it on production!

**Comment by robbosch** [comment]
Thank you @DavidePrincipi 
I am sure it will turn out a stable mirror.

**Comment by DavidePrincipi** [comment]
The mirror is up but is aged: is it running a sync cron job regularly?

**Pull request merged**
